---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 50
  synced_folders:
    - ["<%= File.expand_path(File.dirname(__FILE__)) %>/plugins", "/opt/ohai-plugins/plugins"]
driver_config:
  require_chef_omnibus: latest
provisioner:
  name: chef_solo
platforms:
  - name: ubuntu-12.04
    driver_config:
      box: vagrant-ubuntu-12.04
      box_url: http://files.vagrantup.com/precise64.box
      require_chef_omnibus: true
    run_list:
    - recipe[apt]
    - recipe[chef-unattended-upgrades]
  - name: ubuntu-13.10
    driver_config:
      box: vagrant-ubuntu-13.10
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[apt]
    - recipe[chef-unattended-upgrades]
    attributes:
      apache:
        version: "2.4"
  - name: ubuntu-14.04
    driver_config:
      box: vagrant-ubuntu-14.04
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[apt]
    - recipe[chef-unattended-upgrades]
    attributes:
      apache:
        version: "2.4"
  - name: centos-5
    driver_config:
      box: vagrant-centos-5
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-5.10_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[ohai_plugins_test::disable_ipv6]
    - recipe[yum-cron]
  - name: centos-6
    driver_config:
      box: vagrant-centos-6
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[ohai_plugins_test::disable_ipv6]
    - recipe[yum-cron]
    - recipe[ohai_plugins_test::rhcs]
  - name: debian-6
    driver_config:
      box: vagrant-debian-6
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[apt]
    - recipe[chef-unattended-upgrades]
  - name: debian-7
    driver_config:
      box: vagrant-debian-7
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
      require_chef_omnibus: true
    run_list:
    - recipe[apt]
    - recipe[chef-unattended-upgrades]

suites:
- name: ohaiplugins
  run_list:
    - recipe[build-essential]
    - recipe[git]
    - recipe[mysql::client]
    - recipe[mysql::server]
    - recipe[ohai_plugins_test::default]
    - recipe[ohai_plugins_test::postfix]
    - recipe[ohai_plugins_test::vhosts]
    - recipe[ohai_plugins_test::wordpress]
    - recipe[ohai_plugins_test::magento]
    - recipe[ohai_plugins_test::sophos]
  attributes:
    apt:
      compile_time_update: true
    build_essential:
      compile_time: true
      compiletime: true
    mysql:
      server_root_password: passw0rd
      server_debian_password: passw0rd
      server_repl_password: passw0rd
    ohai_plugins_test:
      pr: <%= ENV['OHAI_PLUGINS_PR'] || nil %>
      ref: <%= ENV['OHAI_PLUGINS_VERSION'] || "HEAD" %>
      ohai:
        ref: <%= ENV['OHAI_VERSION'] || "HEAD" %>
    wordpress:
      server_name: wordpress.example.com
    magento:
      server_name: magento.example.com
